//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_bodegas
    {
        public int id_bodega { get; set; }
        public string nombre_bodega { get; set; }
        public string sucursal { get; set; }
        public string tipo { get; set; }
        public int id_sucursal { get; set; }
        public int id_tipo_bodega { get; set; }
    }
}
