//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppInventario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_login
    {
        public int id_usuario { get; set; }
        public string usuario { get; set; }
        public string clave { get; set; }
        public string nombre_completo { get; set; }
        public string dui { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> estado_sesion { get; set; }
        public Nullable<System.DateTime> fecha_ultimo_ingreso { get; set; }
        public Nullable<System.TimeSpan> hora_ultimo_ingreso { get; set; }
        public Nullable<int> id_rol { get; set; }
    }
}
