//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppInventario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_movimientos
    {
        public string estado { get; set; }
        public int id_movimiento { get; set; }
        public string tipo_movimiento { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<System.TimeSpan> hora { get; set; }
        public string descripcion { get; set; }
        public Nullable<decimal> costo_total_con_iva { get; set; }
        public Nullable<decimal> costo_total_sin_iva { get; set; }
        public string usuario { get; set; }
        public string nombre { get; set; }
    }
}
